### PR TITLE
initial refactor of input parsing 

### PR DESCRIPTION
**Pull request by koomie**
in support of #87. Updates minimum version requirement for libGRVY.

### CODE REVIEW

**Comment by trevilo** [comment]
Looks pretty good to me @koomie.  Two names in the file that I wouldn't mind changing:

* `flow/equations` : maybe `flow/equation_system` instead?
* `viscousSource`: this houses the options to set the spatially dependent viscosity multiplier, correct?  I wouldn't have guessed that based on the name.  Maybe `viscosityMultiplierFunction` or something similar?

Only other question: I can't find where the `viscousSource` options are read in `M2ulPhyS::parseSolverOptions2()`.  Is that an oversight or is it read somewhere else?

**Comment by marc-85** [comment]
I agree with Todd and maybe 'iterFreq' could be something like 'outputFreq', 'dumpFreq' or something like that?

**Comment by koomie** [comment]
> Looks pretty good to me @koomie. Two names in the file that I wouldn't mind changing:
> 
> * `flow/equations` : maybe `flow/equation_system` instead?
> * `viscousSource`: this houses the options to set the spatially dependent viscosity multiplier, correct?  I wouldn't have guessed that based on the name.  Maybe ` or something similar?
> 
> Only other question: I can't find where the `viscousSource` options are read in `M2ulPhyS::parseSolverOptions2()`. Is that an oversight or is it read somewhere else?

Probably an oversight and indication it is not used in any current regression tests.  I can update to `viscosityMultiplierFunction` and update the parsing routine.

**Comment by koomie** [comment]
> I agree with Todd and maybe 'iterFreq' could be something like 'outputFreq', 'dumpFreq' or something like that?

I like `outputFreq` so I'll update that name as well.

**Comment by koomie** [comment]
* Updated `flow/iterFreq` -> `flow/outputFreq`
* `[viscousSource]` -> `[viscosityMultiplerFunction]`
* `flow/equations` -> `flow/equation_system`

**Pull request merged**
