### PR TITLE
Fix isothermal bc

### PR DESCRIPTION
**Pull request by marc-85**
This PR adds viscous terms to the isothermal wall BC and corrects a misspelled word that prevented adiabatic walls from running.

### CODE REVIEW

**Comment by trevilo** [comment]
The code changes look good to me @marc-85.  Three questions:

1. I assume the failing tests are all cases that use the isothermal wall.  Can you confirm that?  If so, just need to update the reference solutions.
2. The GPU tests all pass still.  I suppose that is because this fix only impacts the CPU code path.  Does the GPU path have the same bug though?
3. This PR seems to include the changes from PR #99 as well.  Is that on purpose?

**Comment by marc-85** [comment]
> The code changes look good to me @marc-85. Three questions:
> 
>     1. I assume the failing tests are all cases that use the isothermal wall.  Can you confirm that?  If so, just need to update the reference solutions.
> 
>     2. The GPU tests all pass still.  I suppose that is because this fix only impacts the CPU code path.  Does the GPU path have the same bug though?
> 
>     3. This PR seems to include the changes from PR [Adding passive scalar read for new input file #99](https://github.com/pecos/tps/pull/99) as well.  Is that on purpose?

1. I can confirm that the differences are due to the wall.
2. The GPU wall has not been modified. I will modify it once we have the CPU version cleaned up.
3. That was a mistake. I branched off a branch different than main

**Comment by trevilo** [comment]
Looks like CPU tests are good, but in updating the CPU reference solutions, the GPU tests that depend on the same solutions are failing.  How do we want to handle this?  I see three possibilities:

1. Wait to merge until the GPU code is fixed also
2. Merge now but maintain separate GPU reference solutions for some tests until the GPU code is fixed
3. Merge now and keep the reference solutions the same but mark some GPU tests as XFAIL

I kind of like 3. the best, but it isn't a strong opinion.

**Comment by marc-85** [comment]
Can we hold off a bit? I'm working to get the GPU part fixed. I think I can do this before Monday

**Comment by trevilo** [comment]
> Can we hold off a bit? I'm working to get the GPU part fixed. I think I can do this before Monday

I'm okay with that.  @koomie is probably wanting to start some new runs with this fix, so I'll defer to him.

**Comment by marc-85** [comment]
I'm almost done, I think

**Comment by koomie** [comment]
I can wait; I get great joy in seeing the same results from cpu/gpu.

**Review by trevilo — APPROVED** [review]

**Comment by koomie** [comment]
Since ref solutions changed again, let's get in the habit of documenting the magnitude of the change. Here is a quick look at `cyl3d_coarse.4iters.h5`

* density => O(1.e-8) (absolute)
* rho-u => O(1.e-5) (absolute)
* rho-v => O(1.e-5) (absolute)
* rho-w => O(1.e-7) (relative)

**Pull request merged**
